# Generated by Django 6.0.5 on 2026-06-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_label',
            field=models.CharField(blank=True, default='FOR LEARNERS', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='START BUILDING FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='BROWSE CHALLENGES', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True),
        ),
    ]
