# Generated by Django 6.0.5 on 2026-06-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_clients_section_title_homepageclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='clients_section_title',
        ),
        migrations.DeleteModel(
            name='HomePageClient',
        ),
    ]
