# Generated by Django 6.0.5 on 2026-06-13 14:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_clients_section_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='URL embed YouTube, contoh: https://www.youtube.com/embed/xxx'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_section_label',
            field=models.CharField(blank=True, default='WATCH & LEARN', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_section_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_section_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageVideoStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(help_text='Contoh: 10+, 500+, 24/7', max_length=20)),
                ('label', models.CharField(help_text='Contoh: Years of Experience', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_stats', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
