# Generated by Django 6.0.5 on 2026-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_video_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL, example: https://www.youtube.com/embed/xxx'),
        ),
        migrations.AlterField(
            model_name='homepagevideostat',
            name='label',
            field=models.CharField(help_text='Example: Years of Experience', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagevideostat',
            name='value',
            field=models.CharField(help_text='Example: 10+, 500+, 24/7', max_length=20),
        ),
    ]
