# Generated by Django 6.0.5 on 2026-06-16 04:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_showcase_label_homepage_showcase_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='packages_label',
            field=models.CharField(blank=True, default='OUR SERVICES', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='packages_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='packages_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='Contoh: $999/mo atau Rp 5.000.000', max_length=100)),
                ('description', models.TextField()),
                ('is_popular', models.BooleanField(default=False)),
                ('features_text', models.TextField(blank=True, help_text='Satu fitur per baris')),
                ('button_text', models.CharField(default='Get Started', max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_packages', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
