# Generated by Django 6.0.5 on 2026-06-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_packages_label_homepage_packages_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials_label',
            field=models.CharField(blank=True, default='TESTIMONIALS', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_1_label',
            field=models.CharField(blank=True, default='Happy Clients', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_1_value',
            field=models.CharField(blank=True, default='500+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_2_label',
            field=models.CharField(blank=True, default='Client Satisfaction', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_2_value',
            field=models.CharField(blank=True, default='98%', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_3_label',
            field=models.CharField(blank=True, default='Projects Delivered', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_3_value',
            field=models.CharField(blank=True, default='150+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_4_label',
            field=models.CharField(blank=True, default='Long-Term Partnerships', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_stat_4_value',
            field=models.CharField(blank=True, default='50+', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_subtitle',
            field=models.TextField(blank=True, default='Hear from businesses and organizations that have trusted us to bring their ideas to life.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(blank=True, default='What Our Clients Say', max_length=255),
        ),
    ]
