# Generated by Django 6.0.5 on 2026-06-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_testimonials_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_1_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_1_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_2_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_2_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_3_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_3_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_4_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_stat_4_value',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_title',
        ),
    ]
