# Generated by Django 6.0.5 on 2026-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_packages_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='packages_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='showcase_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
