# Generated by Django 6.0.5 on 2026-06-21 03:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_sitesettings_company_description_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('main_nav', 'Main Navigation'), ('footer_nav', 'Footer Navigation'), ('quick_links', 'Quick Links'), ('legal', 'Legal Menu')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional icon class or emoji', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate from site name and current year', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cta_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cta_url',
            field=models.CharField(blank=True, help_text='Use relative path (e.g. /contact/) or full URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='navigation.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Optional external URL (used if no Page is selected)', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menu'),
        ),
    ]
