# Generated by Django 6.0.5 on 2026-06-21 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_menu_menuitem_icon_menuitem_is_active_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='open_in_new_tab',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_copyright',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_cta_url',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='Optional external URL', max_length=255),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
