# Generated by Django 6.0.5 on 2026-07-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='What Our Clients Say', max_length=255)),
                ('hero_description', models.TextField(blank=True, help_text='Short description displayed below the hero title.')),
                ('cta_title', models.CharField(blank=True, default='Share Your Experience', max_length=255)),
                ('cta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Testimonials Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Company')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project_name', models.CharField(blank=True, max_length=150, verbose_name='Project Name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5)),
                ('testimonial', models.TextField(verbose_name='Testimonial')),
                ('featured', models.BooleanField(default=False, help_text='Display this testimonial in the featured section.')),
                ('published', models.BooleanField(default=False, help_text='Display this testimonial on the website.')),
                ('consent_to_publish', models.BooleanField(default=False, help_text='Client has given permission to publish this testimonial.', verbose_name='Consent to Publish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
